"""creacion_tablas_core

Revision ID: 7b0a9dd523c0
Revises: 
Create Date: 2026-06-23 19:55:30.040721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0a9dd523c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditos_read_model',
    sa.Column('credito_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('monto_solicitado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plazo_meses', sa.Integer(), nullable=False),
    sa.Column('estado_actual', sa.String(length=50), nullable=False),
    sa.Column('score_final', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('credito_id')
    )
    op.create_index(op.f('ix_creditos_read_model_usuario_id'), 'creditos_read_model', ['usuario_id'], unique=False)
    op.create_table('event_store',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credito_id', sa.UUID(), nullable=False),
    sa.Column('evento_tipo', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('firma_digital', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_store_credito_id'), 'event_store', ['credito_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_store_credito_id'), table_name='event_store')
    op.drop_table('event_store')
    op.drop_index(op.f('ix_creditos_read_model_usuario_id'), table_name='creditos_read_model')
    op.drop_table('creditos_read_model')
    # ### end Alembic commands ###
